/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI1;

import static skripsi1.skripsi1.prim;

/**
 *
 * @author Shaula Balqis Z
 */
public class editDataTraining1 extends javax.swing.JFrame {

    /**
     * Creates new form editDataTraining
     */
    public editDataTraining1() {
        initComponents();
        addArea.setEnabled(false);
        errorAdding.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnDefault = new javax.swing.JRadioButton();
        addSeq = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addArea = new javax.swing.JTextArea();
        cancelEdit = new javax.swing.JButton();
        okEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        errorAdding = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ubah Data");

        returnDefault.setText("Gunakan data default");
        returnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnDefaultMouseClicked(evt);
            }
        });

        addSeq.setText("Tambah data (format FASTA)");
        addSeq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSeqMouseClicked(evt);
            }
        });

        addArea.setColumns(20);
        addArea.setRows(5);
        jScrollPane2.setViewportView(addArea);

        cancelEdit.setText("Batal");
        cancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelEditMouseClicked(evt);
            }
        });

        okEdit.setText("OK");
        okEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okEditMouseClicked(evt);
            }
        });

        jLabel1.setText("ATAU");

        errorAdding.setForeground(new java.awt.Color(204, 0, 0));
        errorAdding.setText("errorAdding");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSeq)
                            .addComponent(returnDefault)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorAdding)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSeq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelEdit)
                    .addComponent(okEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelEditMouseClicked
        skripsi1.skripsi1.prim.viewTrainingPattern.setEnabled(true);
        skripsi1.skripsi1.prim.editDataTraining.setEnabled(true);
        skripsi1.skripsi1.prim.ubahParameter.setEnabled(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelEditMouseClicked

    private void addSeqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSeqMouseClicked
        if (addSeq.isSelected()==true){
            returnDefault.setSelected(false);
            addArea.setEnabled(true);
        }
        else{
            returnDefault.setSelected(true);
            addArea.setEnabled(false);
        }
        errorAdding.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_addSeqMouseClicked

    private void okEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okEditMouseClicked
        if (addSeq.isSelected()==true){
            String q=addArea.getText();
            char[] qChar=q.toCharArray();
            if (q.isEmpty()==false&&qChar[0]=='>'){
                fungsi1.dataEdit1.dataAdd(q);
                fungsi1.readFileFasta1.baca();
                fungsi1.sigmoidNormalization1.startTraining();
                fungsi1.sigmoidNormalization1.startTest();
                prim.viewJumlahData.setText(String.valueOf(fungsi1.readFileFasta1.jumlahDataTraining));
                //skripsi1.skripsi1.prim.setEnabled(true);
                skripsi1.skripsi1.prim.viewTrainingPattern.setEnabled(true);
                skripsi1.skripsi1.prim.editDataTraining.setEnabled(true);
                skripsi1.skripsi1.prim.ubahParameter.setEnabled(true);
                this.dispose();
            }
            else if(q.isEmpty()==false&&qChar[0]!='>'){
                errorAdding.setText("Data tidak sesuai format FASTA");
                errorAdding.setVisible(true);
            }
                
            else{
                errorAdding.setText("Tidak ada deret yang ditambahkan");
                errorAdding.setVisible(true);
            }
        }
        else if (returnDefault.isSelected()==true){
            fungsi1.dataEdit1.dataDefault();
            fungsi1.readFileFasta1.baca();
            fungsi1.sigmoidNormalization1.startTraining();
            fungsi1.sigmoidNormalization1.startTest();
            prim.viewJumlahData.setText(String.valueOf(fungsi1.readFileFasta1.jumlahDataTraining));
            skripsi1.skripsi1.prim.viewTrainingPattern.setEnabled(true);
            skripsi1.skripsi1.prim.editDataTraining.setEnabled(true);
            skripsi1.skripsi1.prim.ubahParameter.setEnabled(true);  
            this.dispose();
            //masukin fungsi kalo mau pake default data training 
        }
        else{
            skripsi1.skripsi1.prim.viewTrainingPattern.setEnabled(true);
            skripsi1.skripsi1.prim.editDataTraining.setEnabled(true);
            skripsi1.skripsi1.prim.ubahParameter.setEnabled(true);
            this.dispose();
        }
        
            
        // TODO add your handling code here:*/
    }//GEN-LAST:event_okEditMouseClicked

    private void returnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnDefaultMouseClicked
        if (returnDefault.isSelected()==true){
            addSeq.setSelected(false);
            addArea.setEnabled(false);
        }
        else{
            addSeq.setSelected(true);
            addArea.setEnabled(true);
        }
        errorAdding.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDefaultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDataTraining1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDataTraining1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDataTraining1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDataTraining1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDataTraining1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea addArea;
    private javax.swing.JRadioButton addSeq;
    private javax.swing.JButton cancelEdit;
    private javax.swing.JLabel errorAdding;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okEdit;
    private javax.swing.JRadioButton returnDefault;
    // End of variables declaration//GEN-END:variables
}
