/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI1;

/**
 *
 * @author Shaula Balqis Z
 */
public class start1 extends javax.swing.JFrame {
    private String[] args;
    public static String minErrorV = Double.toString(0.05);
    public static String maxEpochV = Integer.toString(10000);
    public static String alphaV = Double.toString(0.01);
    public static String hid1 = Integer.toString(20);
    public static String hid2 = Integer.toString(15);
    /**
     * Creates new form start
     */
    public start1() {
        initComponents();
        //System.out.println(hid);
        alpha.setText(alphaV);
        hidden1.setText(hid1);
        hidden2.setText(hid2);
        epochmax.setText(maxEpochV);
        minerror.setText(minErrorV);
        alpha.setEnabled(false);
        hidden1.setEnabled(false);
        hidden2.setEnabled(false);
        epochmax.setEnabled(false);
        minerror.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        labelJumlahData = new javax.swing.JLabel();
        editDataTraining = new javax.swing.JButton();
        viewTrainingData = new javax.swing.JButton();
        viewJumlahData = new javax.swing.JLabel();
        viewTrainingPattern = new javax.swing.JButton();
        labelAlpha = new javax.swing.JLabel();
        labelHidden1 = new javax.swing.JLabel();
        ubahParameter = new javax.swing.JRadioButton();
        alpha = new javax.swing.JTextField();
        hidden1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelEpochmax = new javax.swing.JLabel();
        labelMinerror = new javax.swing.JLabel();
        epochmax = new javax.swing.JTextField();
        minerror = new javax.swing.JTextField();
        viewTestData = new javax.swing.JButton();
        labelHidden2 = new javax.swing.JLabel();
        hidden2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        viewJumlahDataUji = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klasifikasi Host Virus H5N1 Segmen M1/M2 Domain Indonesia");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        labelJumlahData.setText("Jumlah Data Latih ");

        editDataTraining.setText("Ubah Data");
        editDataTraining.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editDataTrainingMouseClicked(evt);
            }
        });

        viewTrainingData.setText("Lihat Data Latih");
        viewTrainingData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTrainingDataMouseClicked(evt);
            }
        });

        viewTrainingPattern.setText("Mulai Pelatihan");
        viewTrainingPattern.setToolTipText("");
        viewTrainingPattern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTrainingPatternMouseClicked(evt);
            }
        });

        labelAlpha.setText("Laju Pembelajaran");

        labelHidden1.setText("Neuron Lapisan Tersembunyi 1");

        ubahParameter.setText("Ubah parameter");
        ubahParameter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahParameterMouseClicked(evt);
            }
        });

        alpha.setText("jTextField1");
        alpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaActionPerformed(evt);
            }
        });

        hidden1.setText("jTextField2");

        labelEpochmax.setText("Epoch maksimal");

        labelMinerror.setText("Toleransi Kesalahan");

        epochmax.setText("jTextField3");

        minerror.setText("jTextField4");

        viewTestData.setText("Lihat Data Uji");
        viewTestData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTestDataMouseClicked(evt);
            }
        });
        viewTestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTestDataActionPerformed(evt);
            }
        });

        labelHidden2.setText("Neuron Lapisan Tersembunyi 2");

        hidden2.setText("jTextField2");

        jLabel1.setText("Jumlah Data Uji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelHidden1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hidden1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelHidden2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hidden2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEpochmax)
                            .addComponent(labelMinerror))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(epochmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minerror, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewJumlahData)
                            .addComponent(viewJumlahDataUji, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewTrainingPattern, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editDataTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewTrainingData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubahParameter)
                            .addComponent(labelAlpha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJumlahData)
                    .addComponent(viewJumlahData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(viewJumlahDataUji))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDataTraining)
                    .addComponent(viewTrainingData)
                    .addComponent(viewTestData))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ubahParameter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHidden1)
                    .addComponent(labelEpochmax)
                    .addComponent(epochmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hidden1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinerror)
                    .addComponent(minerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHidden2)
                    .addComponent(hidden2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlpha)
                    .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewTrainingPattern)
                .addContainerGap())
        );

        labelJumlahData.getAccessibleContext().setAccessibleName("labelJumlahData");
        editDataTraining.getAccessibleContext().setAccessibleName("editDataTraining");
        viewTrainingData.getAccessibleContext().setAccessibleName("viewTrainingData");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewTrainingDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTrainingDataMouseClicked
        String a="";
        for (int i=1; i<=fungsi1.readFileFasta1.jumlahDataTraining; i++){
            a=a+"\n"+String.valueOf(i)+"\n";
            for (int j=1; j<5; j++)
                        a=a+(fungsi1.readFileFasta1.dataRawTraining[j][i-1])+"\n";
        }
        UI1.viewDataTraining1 view=new UI1.viewDataTraining1();
        view.setVisible(true);
        view.viewArea.setText(a);
        //this.setEnabled(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_viewTrainingDataMouseClicked

    private void viewTrainingPatternMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTrainingPatternMouseClicked
      if (viewTrainingPattern.isEnabled()==true){  
        double nilaiAlpha=Double.parseDouble(alpha.getText());
        int nilaiHidden1=Integer.parseInt(hidden1.getText());
        int nilaiHidden2=Integer.parseInt(hidden2.getText());
        int nilaiEpochmax=Integer.parseInt(epochmax.getText());
        double nilaiToleransierror=Double.parseDouble(minerror.getText());
        fungsi1.init1.inisialisasi(nilaiAlpha,nilaiHidden1,nilaiHidden2,nilaiEpochmax,nilaiToleransierror);
        fungsi1.training1.main(args);
        viewTrainingPattern.setEnabled(false);
        editDataTraining.setEnabled(false);
        ubahParameter.setEnabled(false);
      }  
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTrainingPatternMouseClicked

    private void alphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphaActionPerformed

    private void ubahParameterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahParameterMouseClicked
        if (ubahParameter.isSelected()==true){
            alpha.setEnabled(true);
            hidden1.setEnabled(true);
            hidden2.setEnabled(true);
            epochmax.setEnabled(true);
            minerror.setEnabled(true);
        }
        else{
            /*alpha.setText(alphaV);
            hidden1.setText(hid1);
            hidden2.setText(hid2);
            epochmax.setText(maxEpochV);
            minerror.setText(minErrorV);*/
            alpha.setEnabled(false);
            hidden1.setEnabled(false);
            hidden2.setEnabled(false);
            epochmax.setEnabled(false);
            minerror.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahParameterMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        //System.out.println(hid);
        /*alpha.setText(alphaV);
        hidden1.setText(hid1);
        hidden2.setText(hid2);
        epochmax.setText(maxEpochV);
        minerror.setText(minErrorV);*/
        alpha.setEnabled(false);
        hidden1.setEnabled(false);
        hidden2.setEnabled(false);
        epochmax.setEnabled(false);
        minerror.setEnabled(false);
        ubahParameter.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void viewTestDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTestDataMouseClicked
        String a="";
        for (int i=1; i<=fungsi1.readFileFasta1.jumlahDataTest; i++){
            a=a+"\n"+String.valueOf(i)+"\n";
            for (int j=1; j<5; j++)
                        a=a+(fungsi1.readFileFasta1.dataRawTest[j][i-1])+"\n";
        }
        UI1.viewDataTest1 view=new UI1.viewDataTest1();
        view.setVisible(true);
        view.viewArea.setText(a);
        //this.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_viewTestDataMouseClicked

    private void editDataTrainingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editDataTrainingMouseClicked
      if (editDataTraining.isEnabled()==true){  
        UI1.editDataTraining1 edit=new UI1.editDataTraining1();
        edit.setVisible(true);
        viewTrainingPattern.setEnabled(false);
        editDataTraining.setEnabled(false);
        ubahParameter.setEnabled(false);
      }
      // TODO add your handling code here:
    }//GEN-LAST:event_editDataTrainingMouseClicked

    private void viewTestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTestDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTestDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alpha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JButton editDataTraining;
    private javax.swing.JTextField epochmax;
    private javax.swing.JTextField hidden1;
    private javax.swing.JTextField hidden2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAlpha;
    private javax.swing.JLabel labelEpochmax;
    private javax.swing.JLabel labelHidden1;
    private javax.swing.JLabel labelHidden2;
    public javax.swing.JLabel labelJumlahData;
    private javax.swing.JLabel labelMinerror;
    private javax.swing.JTextField minerror;
    public javax.swing.JRadioButton ubahParameter;
    public static javax.swing.JLabel viewJumlahData;
    public static javax.swing.JLabel viewJumlahDataUji;
    private javax.swing.JButton viewTestData;
    public javax.swing.JButton viewTrainingData;
    public javax.swing.JButton viewTrainingPattern;
    // End of variables declaration//GEN-END:variables
}
